let data = [
  {
    id: 1,
    title: "OnDot",
    detail:
      "Constant Upgrade / Deployment of Application on all platforms with Quality standards for Banking Apps. Improved delivery times, TAT is reduced considerable due to quality and fast development processs.",
    industry: "Technology",
    project: "Web app, Mobile App, Analytics, Banking App ",
    tags: ["Fintech", "Mobile apps"],
    duration: "8 Months",
    technology: [
      { name: "IOS", img: "/icons/apple.png" },
      { name: "Android", img: "/icons/android.png" },
      { name: "AWS", img: "/icons/aws.png" },
      { name: "HTML5", img: "/icons/html.png" },
    ],
    problem: [
      "Development of mobile app with latest upgrades and UI",
      "API integration ",
      "Intergration of security featutes on the App as per International Banking Norms",
      " Customer Facing consultancy",
      "White Labeling of the Apps for various Banks Internationally ",
      "Development in secure confidential environment to conform banking security mandate",
      "Reduce Turn Around Time - TAT",
    ],
    solution: [
      "Professional development and Deployment on tight timelines ",
      "Weekly updates, resource onboarding & allocations, and technical discussions available by onshore account manager",
      "All development project processes overseen by offshore PM",
      " Provided secured work area to conform banking needs",
    ],
    result: [
      "Constant Upgrade / Deployment of Applications on all platforms with Quality standards for Banking Apps",
      "Weekly Sprint management professional for quality applications",
      "Improved delivery times, TAT is reduced considerably due to quality and fast development processes.",
      " Active Client since 2013 till date. ",
    ],
    logoimg: "/portfolio/ondotLogo.png",
    heroimg: "/portfolio/ondotHero.png",
    bigimg: "/portfolio/ondot.webp",
    mainimg: "/portfolio/ondot1.png",
    image: "/portfolio/1.png",
  },
  {
    id: 2,
    title: "Premon Asia",
    detail:
      "<h3>Real-time Analytics For Automotive Industry</h3><p>Increased efficiency for OEMs and Auto dealers Interation of New technology to enhance speed and efficiency of the system. ROI on support is excellent as the India team manages critical tasks at a reasonable cost.</p>",
    industry: "Automobile Survey Analysis.",
    project: "Web Portals & Mobile Apps",
    tags: ["automobile", "Web Portal", "Mobile Apps"],
    duration: "6 Months",
    technology: [
      { name: "IOS", img: "/icons/apple.png" },
      { name: "Android", img: "/icons/android.png" },
      { name: "React JS", img: "/icons/react.png" },
      { name: "Dot Net", img: "/icons/net.png" },
    ],
    problem: [
      "Create B2B mobile and web application with Analytics of survey",
      "Develop algorithms process huge data and generate results ",
      "Compare quarter wise results for better understanding",
      " Make dashboards for automobile dealers and OEMs with relevant real time data",
      " Capture real-time responses and generate quality progressive reports",
      "Created “Action Plan” – automated work flow to manage issues by relevant users in the work plan.",
      "Messaging platform to speed up communication on one platform .",
      "Multi brand solution – i.e. MG, Toyota , Renault etc",
      "Premon CMS to manage OEMs.",
      "Maintenance & Enhancement of the product is on going",
    ],
    solution: [
      "Development of the Android / IOS based mobile application",
      "Tight Sprints for support and development",
      "Analytics module to track work flow and data on web mobule",
      "Project Live , duration 6 months ",
      "Ensure client and NSS development teams work seamlessly",
      "Extensive data processing and client engagements",
    ],
    result: [
      "Flawless user ready mobile application",
      "Increased efficiency for OEMs and Auto dealers",
      "Interation of New technology to enhance speed and efficiency of the system.",
      "ROI on support is excellent as India team manages critical tasks at reasonable cost.",
      "Flexible model of engagement to make client experience seamless",
      "Premon got many big car manufacturers on board based on our quality work ",
    ],
    logoimg: "/portfolio/premonLogo.png",
    heroimg: "/portfolio/premonHero.png",
    bigimg: "/portfolio/premon.webp",
    mainimg: "/portfolio/premon1.png",
    image: "/portfolio/1.png",
  },
  {
    id: 3,
    title: "Modifi",
    detail:
      "Create a workflow app in minutes to collect and calibrate task information from throughout your organisation. Use the powerful analytic dashboard system to drive more thoughtful decisions.",
    industry: "Technology.",
    project: "Web Portals & Mobile Apps.",
    duration: "24 Months",
    tags: ["IOT", "Web Portals", "Mobile Apps"],
    technology: [
      { name: "IOS", img: "/icons/apple.png" },
      { name: "Android", img: "/icons/android.png" },
      { name: "Node JS", img: "/icons/node.png" },
      { name: "Angular JS", img: "/icons/angular.png" },
    ],
    problem: [
      "Create Work Flow templates with pre set components. using web platform",
      "Using IOT to publish the template on Android and IOS Platforms as mobile Application.",
      "Data Publishing challenge , had to keep connection open for publishing data through IOT , using MQTT. Data size was Huge spanning to 2-3 days.",
      "Manage off line and online connectivity and sync data acccordingly.",
    ],
    solution: [
      "Development of the Android / IOS based mobile application",
      "Upgrade of Legacy system to new and enhanced mobile app",
      "Tight Sprints for support and development",
      "Analytics module to track work flow and data on web mobule",
      " Project Live , duration 2 years ",
      "Ensure offshore and onshore development teams work seamlessly",
    ],
    result: [
      "Flawless user ready mobile application",
      "Increased efficiency across all business processes",
      "Interation of New technology to enhance speed and effeciency of the system.",
      " ROI on support is excellent as India team manages critical tasks at reasonable cost.",
      " Healthy fun loving culture across the globe",
    ],
    logoimg: "/portfolio/modifiLogo.png",
    heroimg: "/portfolio/modifiHero.png",
    bigimg: "/portfolio/modifi.webp",
    mainimg: "/portfolio/modifi1.png",
    image: "/portfolio/1.png",
  },
  {
    id: 4,
    title: "All new Again",
    detail:
      "All New Again app is a social app for both individuals and entrepreneurs over which they can share their posts, videos, and thoughts and even promote their respective business links.",
    industry: "Reconstruction & Damage restoration services.",
    project: "Sync data with damage restoration company.",
    tags: ["Reconstruction", "PWA", "Mobile Apps"],
    duration: "6 Months",
    technology: [
      { name: "React", img: "/icons/react.png" },
      { name: "Angular", img: "/icons/angular.png" },
      { name: "Nodejs", img: "/icons/node.png" },
      { name: "Firebase", img: "/icons/firebase.png" },
    ],
    problem: [
      "Create a mobile app to transform excel and other manual files and folders to complete digital form.",
      "Create a web application to monitor the progress of actual work being done across multiple sites by multiple workers and technicians Android App for clients to store and review data with doctors",
      "Conversion of excel sheet formulae that they use into algorithms so that required amount of raw material can be ordered to avoid wastages.",
      "Make a dashboard for administrators with relevant real time data.",
      "Capture real time responses regarding the various works in progress.",
      "Form can be submitted using the mobile app and needs to be saved in the form of a PDF",
    ],
    solution: [
      "Development of the progressive web application and web portal.",
      "Progressive web app that works on iOS and android phones.",
      "Tight sprints for support and development.",
      "Project live duration 6 months – various different features are still being added on continual basis to ease their employees task.",
      "Ensure client and NSS development teams work seamlessly",
      "Extensive data processing and client engagements.",
    ],
    result: [
      "Flawless user ready progressive web application",
      "Technicians can draw sketches showing positions of various equipment placed across the room so that employees at the office can track the numbers of equipment in use.",
      "Using the portal an estimate can be created for bid for the proposed work.",
      "Potential customers can be entered into the system in the form of Lead and can be assigned to a manager who can then take the charge of the proposed work.",
      "Various invoices can be uploaded into the system in the form of purchase order to track the expenses.",
    ],
    logoimg: "/portfolio/allnewagainLogo.png",
    heroimg: "/portfolio/allnewagainHero.png",
    bigimg: "/portfolio/allnewagain.webp",
    mainimg: "/portfolio/allnewagain1.png",
    image: "/portfolio/1.png",
  },
  {
    id: 5,
    title: "Milap",
    detail:
      "Created a Perfect App with all the animation’s and rotation of the newspaper in different direction.Interation of New technology to enhance speed and effeciency of the system.",
    industry: "Technology.",
    project: "Web Portals & Mobile Apps",
    tags: ["Media", "Web Portals", "Mobile Apps"],
    duration: "2 Months",
    technology: [
      { name: "IOS", img: "/icons/apple.png" },
      { name: "Android", img: "/icons/android.png" },
      { name: "React JS", img: "/icons/react.png" },
      { name: "Dot Net", img: "/icons/net.png" },
    ],
    problem: [
      "Create mobile and web application with Urdu Content.",
      "Develop a complete different App with animation and responsiveness.",
      "To Create a backend process to allow user to publish daily content. On both web and mobile App at the same time.",
      "Need to rotate the newspaper in Left to right direction so it turns like a urdu newspaper.",
      "To create a space where milap team can provide users important new instantly.",
      "to link there other social media platform with there App and E-newspaper.",
    ],
    solution: [
      "Development of the Android / IOS based mobile application",
      "Tight Sprints for support and development",
      "Project Live , duration 2 months ",
      "Ensure client and NSS development teams work seamlessly",
      "Extensive data processing and client engagements",
    ],
    result: [
      "Flawless user ready mobile application",
      "Created a Perfect App with all the animation’s and rotation of the newspaper in different direction.",
      "Interation of New technology to enhance speed and effeciency of the system.",
      " Created a Admin panel so the the milap team can mange uploading of newspaper and breaking news whenever they want.",
      "Also linked there social media accounts with the web & mobile App . So the user don’t miss any important news .",
    ],
    logoimg: "/portfolio/milapLogo.png",
    heroimg: "/portfolio/milapHero.png",
    bigimg: "/portfolio/milap.webp",
    mainimg: "/portfolio/milap1.png",
    image: "/portfolio/1.png",
  },
];

export default data;
